### ISSUE TITLE
bug in for loop variables

### ISSUE THREAD

**Issue by walteh** [walteh/retab#33]
```hcl

GO_PACKAGE = "github.com/walteh/xyz"

pkgs = {
	"pkg/core/v1" = ["Golangable"]
	"pkg/schema" = ["ToolProvider"]
}

gen mockery {
	schema = ""
	path   = "../.mockery.yaml"
	data = {
		packages = {
			for pkg, name in pkgs : "${GO_PACKAGE}/${pkg}" => {
				interfaces = {
					for interfac in name : interfac => {}
				}
			}
		}
	}
}

```

creates

```yaml
packages:
    github.com/walteh/xyz/pkg/core/v1:
        interfaces:
            Golangable: {}
    github.com/walteh/xyz/pkg/schema:
        interfaces:
            Golangable: {}
```
