### ISSUE TITLE
another bug in for loops 

### ISSUE THREAD

**Issue by walteh** [walteh/retab#34]
extension of #33 - but different problem 

```hcl
TOOLS_DIR = "tools"

bins = {
	"task"          = "github.com/go-task/task/v3/cmd/task"
	"retab"         = "github.com/walteh/retab/cmd/retab"
	"buf"           = "github.com/bufbuild/buf/cmd/buf",
	"mockery"       = "github.com/vektra/mockery/v2",
	"gotestsum"     = "gotest.tools/gotestsum",
	"golangci-lint" = "github.com/golangci/golangci-lint/cmd/golangci-lint",
}

gen taskfile {
	// schema = "https://taskfile.dev/schema.json"
	path = "../taskfile.yaml"
	data = {
		version = 3
		tasks =
			{
				for bin, path in bins : "${bin}-bin" => {
					generates = ["bin/${bin}"]
					dir       = "${TOOLS_DIR}"
					sources   = ["go.mod", "go.sum", "main.go"]
					cmds = [
						"go build -mod=vendor -o ./bin/${bin} ${path}"
					]
				}
			}
	}
}
```

produces 

```yaml
# code generated by retab. DO NOT EDIT.
# join the fight against yaml @ github.com/walteh/retab

# source: ".retab/task.retab"

version: 3
tasks:
    task-bin: task-bin
    retab-bin: retab-bin
    buf-bin: buf-bin
    mockery-bin: mockery-bin
    gotestsum-bin: gotestsum-bin
    golangci-lint-bin: golangci-lint-bin
```
